# Secrets Manager: sentbiz/dev/datasource
# Keys: DB_URL, DB_USERNAME, DB_PASSWORD, REDIS_HOST, REDIS_PORT,
#        S3_BUCKET, S3_ACCESS_KEY, S3_SECRET_KEY
ark:
  secrets:
    manager:
      secret-id: sentbiz/dev/datasource
      region: ap-northeast-2

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
